name: stt签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: mskelton/setup-yarn@v1.1.0
    - run: yarn install
    - name: Run
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: node src/index
